import "./globals.css";
import localFont from "next/font/local";

const academyFont = localFont({
  src: "./AcademyEngravedLetPlain.woff",
  display: "swap",
  variable: "--font-academyFont",
});

const gtPressura = localFont({
  src: "./gt-pressura-regular.woff",
  display: "swap",
  variable: "--font-gtPressura",
});

const gtPressuraMonoBold = localFont({
  src: "./gt-pressura-mono-bold.woff",
  display: "swap",
  variable: "--font-gtPressuraMonoBold",
});

const gtPressuraMono = localFont({
  src: "./gt-pressura-mono-regular.woff",
  display: "swap",
  variable: "--font-gtPressuraMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${academyFont.variable} ${gtPressura.variable} ${gtPressuraMonoBold.variable} ${gtPressuraMono.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
